### ISSUE TITLE
security alert lucene

### ISSUE THREAD

**Issue by jurgenvinju** [usethesource/docs.rascal-mpl.org-search-engine#1]
![image](https://user-images.githubusercontent.com/1990295/48267822-9f302e00-e433-11e8-9c63-daa3bdd22211.png)

**Comment by DavyLandman** [comment]
Fixed, also fixed on usethesource/rascal

( I updated the dependency to latest lucene, and I had to change a deprecated API call, such that boosting is not done during index building but during query time)
