### ISSUE TITLE
502 booboo

### ISSUE THREAD

**Issue by jurgenvinju** [usethesource/docs.rascal-mpl.org-search-engine#2]
![image](https://user-images.githubusercontent.com/1990295/48267867-bbcc6600-e433-11e8-9b7c-f024cdd38257.png)

**Comment by jurgenvinju** [comment]
note this is the unstable deployment

**Comment by DavyLandman** [comment]
First off: classy issue title ;)

Fixed, the search server was started with systemd, but I forgot to `enable` it, so after a reboot of the server, systemd never started the search engine. this is fixed now.
